### ISSUE TITLE
test报错：No module named 'hat'

### ISSUE THREAD

**Issue by wsl1999** [korouuuuu/HMA#4]
如何解决
  File "d:\hma\hma\archs\__init__.py", line 11, in <module>
    _arch_modules = [importlib.import_module(f'hat.archs.{file_name}') for file_name in arch_filenames]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'hat'

**Comment by Arcitec** [comment]
Same for me. HAT is another upscaler project. Did author @korouuuuu forget to include it in requirements?

- Python 3.8
- Dependencies: `pip install "numpy==1.21.5" "ipython==7.21.0" "opencv-python==4.5.4.58" "torch==2.0.1" "torchvision==0.15.2" "einops==0.4.1" "basicsr==1.4.2"` (because the recommended basicsr does not compile so I used the latest instead)

Executing with this (path is set because it's the only way HMA can find its own modules):

```sh
env PYTHONPATH="$(pwd)" python hma/test.py -opt options/test/HMA_SRx2.yml
```

Error:

```
/HMA/.venv/lib/python3.8/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "hma/test.py", line 4, in <module>
    import hma.archs
  File "/HMA/hma/hma/__init__.py", line 3, in <module>
    from .data import *
  File "/HMA/hma/hma/data/__init__.py", line 11, in <module>
    _dataset_modules = [importlib.import_module(f'hat.data.{file_name}') for file_name in dataset_filenames]
  File "/HMA/hma/hma/data/__init__.py", line 11, in <listcomp>
    _dataset_modules = [importlib.import_module(f'hat.data.{file_name}') for file_name in dataset_filenames]
  File "/home/johnny/.pyenv/versions/3.8.20/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'hat'
```

**Comment by Arcitec** [comment]
Hmm. I noticed that the https://github.com/XPixelGroup/HAT project structure is nearly identical to HMA, and that the requirements are identical. HMA is basically a copy-paste of HAT with some network architecture changes (I guess) and better training. So the solution is simple: Copy-paste the `hat` directory from HAT's repo to HMA.

In my case, I did this:

```sh
git clone https://github.com/korouuuuu/HMA.git
git clone https://github.com/XPixelGroup/HAT.git
ln -srv HAT/hat hma/hat
```

This gave me progress. Now I have a BasicSR error instead, so I guess I went to too far with my BasicSR version upgrade. :D

**Comment by Arcitec** [comment]
Okay I have figured out every problem with this repo:

1. It needs code from the HAT repo that it was based on. Which for some reason wasn't included here.
2. The BasicSR package cannot be installed at the same time as Torch. It must be installed AFTER Torch.

To fix all issues, here's my install steps:

```sh
pyenv local 3.8
python -m venv .venv
source ".venv/bin/activate"

# Manually install requirements based on cog.yaml since requirements.txt is wrong.
pip install --upgrade pip
pip install "numpy==1.21.5" "ipython==7.21.0" "opencv-python==4.5.4.58" "torch==2.0.1" "torchvision==0.15.2" "einops==0.4.1"
pip install "basicsr==1.3.4.9"

# Fix HAT dependency.
git clone https://github.com/korouuuuu/HMA.git
git clone https://github.com/XPixelGroup/HAT.git
ln -srv HAT/hat HMA/hat

# Write necessary version metadata.
cd HMA
python setup.py develop

# Now run, with PYTHONPATH because nothing is correct about how this package searches for modules.
env PYTHONPATH="$(pwd)" python hma/test.py -opt options/test/HMA_SRx2.yml
```

But there's still one more problem. Of course! :D

Error:

```
HMA/.venv/lib/python3.8/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "hma/test.py", line 4, in <module>
    import hma.archs
  File "HMA/test/HMA/hma/__init__.py", line 3, in <module>
    from .data import *
  File "HMA/test/HMA/hma/data/__init__.py", line 11, in <module>
    _dataset_modules = [importlib.import_module(f'hat.data.{file_name}') for file_name in dataset_filenames]
  File "HMA/test/HMA/hma/data/__init__.py", line 11, in <listcomp>
    _dataset_modules = [importlib.import_module(f'hat.data.{file_name}') for file_name in dataset_filenames]
  File "/home/johnny/.pyenv/versions/3.8.20/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'hat.data.paired_imagenet_dataset'
```

This error is because hat's file is named `hat.data.imagenet_paired_dataset` but for some reason HMA tries to import `hat.data.paired_imagenet_dataset` instead.

So yeah this repo is a mess but the work itself looks so awesome that I really hope someone figures out the rest of these bugs!

**Comment by Arcitec** [comment]
Ah I have probably figured out the real reason for the error.

HMA names its own file `hma/data/paired_imagenet_dataset.py`

HAT names its own file `hat/data/imagenet_paired_dataset.py`

HMA contains `__init__.py` files in each subdir that still refer to the `hat.` project, which scans for all files in the directory and then tries to load the `hat.` variant, so it ends up trying to load the HAT version of that file but with the HMA filename.

I will figure this out soon, but I will not delete my previous troubleshooting messages. I want people to feel the same pain I felt. :)

**Comment by Arcitec** [comment]
# Solved.

So, the bug was actually that HMA took HAT's code, but did not properly rewrite the folder/includes to the new HMA name instead. It does NOT need HAT as a dependency. It's just very clear that koro did development with the files still named "hat", and then hastily renamed them to "hma" when publishing, without realizing that they are still trying to import hat code.

Here's the final fixed instructions, until this repo is fixed:

```sh
pyenv local 3.8
python -m venv .venv
source ".venv/bin/activate"

# Manually install requirements based on cog.yaml since requirements.txt is wrong (it's wrong in HAT too).
pip install --upgrade pip
pip install "numpy==1.21.5" "ipython==7.21.0" "opencv-python==4.5.4.58" "torch==2.0.1" "torchvision==0.15.2" "einops==0.4.1"

# We must install BasicSR AFTER Torch (not on the same line), otherwise it will not install at all.
pip install "basicsr==1.3.4.9"

# Clone HMA.
git clone https://github.com/korouuuuu/HMA.git

# Fix old references to HAT in the code. It's a problem in the __init__.py files.
find HMA -name "__init__.py" -exec sed -i"" -E 's,\bhat\.,hma.,g' "{}" \;

# Write necessary version metadata.
cd HMA
python setup.py develop

# Now run, with PYTHONPATH because nothing is correct about how this package searches for modules (HAT has the same problem).
env PYTHONPATH="$(pwd)" python hma/test.py -opt options/test/HMA_SRx2.yml
```

Of course, the project still breaks with another error now. This is the same BasicSR error I saw earlier when I thought my BasicSR was "too new", but now it's the exact version recommended and it's still not working.

So the final conclusion is: This repo is very broken in many ways. I have fixed MOST of the bugs with my steps above, but there's more bugs and I am too tired to continue. @korouuuuu :)

```
env PYTHONPATH="$(pwd)" python hma/test.py -opt options/test/HMA_SRx2.yml
Traceback (most recent call last):
  File "hma/test.py", line 4, in <module>
    import hma.archs
  File "HMA/test/HMA/hma/__init__.py", line 3, in <module>
    from .data import *
  File "HMA/test/HMA/hma/data/__init__.py", line 11, in <module>
    _dataset_modules = [importlib.import_module(f'hma.data.{file_name}') for file_name in dataset_filenames]
  File "HMA/test/HMA/hma/data/__init__.py", line 11, in <listcomp>
    _dataset_modules = [importlib.import_module(f'hma.data.{file_name}') for file_name in dataset_filenames]
  File "/home/johnny/.pyenv/versions/3.8.20/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "HMA/test/HMA/hma/data/paired_imagenet_dataset.py", line 9, in <module>
    from basicsr.utils import FileClient, imfrombytes, img2tensor, rgb2ycbcr
ImportError: cannot import name 'rgb2ycbcr' from 'basicsr.utils' (HMA/test/.venv/lib/python3.8/site-packages/basicsr/utils/__init__.py)
```

Edit: Just as a quick check, I looked at the latest BasicSR code and see that they have this function, but it's NOT in `basicsr.utils.rgb2ycbcr`. It's in `basicsr.utils.color_util.rgb2ycbcr`:

https://github.com/search?q=repo%3AXPixelGroup%2FBasicSR%20rgb2ycbcr&type=code

This was also the situation in the EXACT, OLD version of BasicSR that both HAT and HMA claim that they need. Except that in those old versions, it was instead inside `basicsr.utils.matlab_functions.rgb2ycbcr`. So both HAT and HMA's code are such a gigantic mess, lol. I have spent 2 hours on this!

Here's the fix for the FINAL error:

- Open `hma/data/paired_imagenet_dataset.py` in a text editor.
- Delete this line:
```py
from basicsr.utils import FileClient, imfrombytes, img2tensor, rgb2ycbcr
```
- Use these lines instead:
```py
from basicsr.utils import FileClient, imfrombytes, img2tensor
from basicsr.utils.matlab_functions import rgb2ycbcr
```

**Now the code FINALLY runs. Jeeeesus.**

**Comment by Arcitec** [comment]
Thanks @korouuuuu I was just cloning your repo now to fix bugs and submit PR but I see you started editing already. <3

**Comment by Arcitec** [comment]
Alright, I've submitted the fix for the BasicSR imports. After #5 is merged, the "only" things people have to do to run this locally are these steps:

```sh
pyenv local 3.8
python -m venv .venv
source ".venv/bin/activate"

# Manually install requirements based on cog.yaml since requirements.txt is wrong (it's wrong in HAT too).
pip install --upgrade pip
pip install "numpy==1.21.5" "ipython==7.21.0" "opencv-python==4.5.4.58" "torch==2.0.1" "torchvision==0.15.2" "einops==0.4.1"

# We must install BasicSR AFTER Torch (not on the same line), otherwise it will not install at all.
# NOTE: Newer versions of BasicSR can be installed on the same line as Torch, but I don't dare
# to try upgrading since it would definitely break HMA due to BasicSR changes in newer versions. ;)
pip install "basicsr==1.3.4.9"

# Clone HMA.
git clone https://github.com/korouuuuu/HMA.git

# Write necessary version metadata.
cd HMA
python setup.py develop

# Now run, with PYTHONPATH because nothing is correct about how this package searches for modules (HAT has the same problem).
env PYTHONPATH="$(pwd)" python hma/test.py -opt options/test/HMA_SRx2.yml
```

And yes, I use [pyenv](https://github.com/pyenv/pyenv?tab=readme-ov-file#automatic-installer) to install Python 3.8, since that's the version that HAT/HMA requires.

Update: I have finally used it and tried x4 upscaling. The results are fantastic. It does not handle compression artifacts/denoising whatsoever (it literally makes compression artifacts SHARPER and more visible), so you MUST give it high-quality input, but then it will produce high-quality output! I used a 1120x1680 image as PNG as my Ground Truth, downsized to 25% (280x420) as PNG as my Low Res (which made it very blurry and lost almost all textures/details, as intended), then upscaled with HMA x4. Result was very sharp and surprisingly close to the ground truth. Of course there a was loss of details/textures since the 25% downscale lost a LOT of details, but that's expected. I then tried upscaling a 2K image to 8K and it basically looked like native 8K, with no sign of upscaling artifacts. HMA is an amazing model!

**Comment by wsl1999** [comment]
@Arcitec  Thanks for your determination!! Your bug-fix experience really inspires me, I will try your fix solution on weekend.

**Comment by surfingnirvana** [comment]
How to test a single image?
